# Noydra buraya java dosya yolu belirtme l?tfen local.properties i?erisinde belirt.
kotlin.code.style=official
kotlin.mpp.enableCInteropCommonization=true
kotlin.mpp.androidSourceSetLayoutVersion=2
android.useAndroidX=true
android.nonTransitiveRClass=true
android.suppressUnsupportedCompileSdk=35
org.gradle.jvmargs=-Xmx3g -Dfile.encoding=UTF-8
org.gradle.parallel=true
org.gradle.caching=true

tor.bundle.version=15.0.24
tor.sha256.windows.x86_64=e9dc6ccc93cd6afa507193f4de284d6424233ff5102155cd2c94b259e8a22b65
tor.sha256.linux.x86_64=8e012ec6815d7899cb64011582e2dade88e74119c6661068a2a3252de0ccd7f2
tor.sha256.macos.x86_64=8acb0b590f6be34084dcb6d84009ac0c61cc7c5261b7a19d2ab94845aa9bd5b6
tor.sha256.macos.aarch64=d47afd04b6c751129978390ad003d74ac8b88adfbb939350f0f89999e6570644
tor.sha256.android.aarch64=2a7a02484149b05f64b582a4a1e8eb8aabb9f6cd32daca4e03c58e09839bb7a8
tor.sha256.android.armv7=9416f72b9cd31eda0f7f5a1fa3e2eec789b88b8160e20f5d690bc4ba8c29811e
tor.sha256.android.x86_64=500d51006f1938dfd5ecd0653b0d2a156feff8a4dc5e2b61b81793d47854fc90
tor.sha256.android.x86=32532b4250d5823f07ac2d88197908c1d11ffa015354144d295ee64302107917

org.gradle.tooling.parallel=true
